version: '3'
services:
  emailing:
    image: emailing
    build: EmailingService/.
    ports:
      - "3000:3000"
    environment:
      - port=3000
  newscomposition:
    image: newscomposition
    build: NewsCompositionService/.
    ports:
      - "3001:3001"
    environment:
      - port=3001
  newspage:
    image: newspage
    build: NewsPageService/.
    ports:
      - "3002:3002"
    environment:
      - port=3002
  subscription:
    image: subscription
    build: SubscriptionService/.
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - JWT=teamsuperman
