version: '3'
services:
  emailingservice:
    build: './EmailingService'
    ports:
      - "11001:11001"

  newscompositionservice:
    build: './NewsCompositionService'
    ports:
      - "11002:11002"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  newspageservice:
    build: './NewsPageService'
    ports:
      - "11003:11003"

  subscriptionservice:
    build: './SubscriptionService'
    ports:
      - "11004:11004"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
  
  db:
    image: mongo
    ports:
      - "27017:27017"
