version: '3'
services:
  emailing:
    image: emailing
    build: EmailingService/.
    ports:
      - "3000:3000"
    environment:
      - port=3000
    depends_on:
      - mongo
  newscomposition:
    image: newscomposition
    build: NewsCompositionService/.
    ports:
      - "3001:3001"
    environment:
      - port=3001
      - MONGO_DB_URI=mongodb://teamsuperman:teamsuperman@mongo:27017/admin?ssl=false
    depends_on:
      - mongo
  newspage:
    image: newspage
    build: NewsPageService/.
    ports:
      - "3002:3002"
    environment:
      - port=3002
  subscription:
    image: subscription
    build: SubscriptionService/.
    ports:
      - "3003:3003"
    environment:
      - port=3003
      - MONGO_DB_URI=mongodb://teamsuperman:teamsuperman@mongo:27017/admin?ssl=false
      - JWT=teamsuperman
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=teamsuperman
      - MONGO_INITDB_ROOT_PASSWORD=teamsuperman