version: '3'
services:
  emailingservice:
    build: './EmailingService'
    ports:
      - "7000:7000"

  newscompositionservice:
    build: './NewsCompositionService'
    ports:
      - "8000:8000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices

  newspageservice:
    build: './NewsPageService'
    ports:
      - "5000:5000"

  subscriptionservice:
    build: './SubscriptionService'
    ports:
      - "4000:4000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
  
  db:
    image: mongo
    ports:
      - "27017:27017"
